import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_fragment_ktx: String = "android.arch.navigation:navigation-fragment-ktx:" +
      Versions.android_arch_navigation

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_fragment: String = "android.arch.navigation:navigation-fragment:" +
      Versions.android_arch_navigation

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_ui_ktx: String = "android.arch.navigation:navigation-ui-ktx:" +
      Versions.android_arch_navigation

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
      Versions.androidx_databinding

  /**
   * https://developer.android.com/studio
   */
  const val databinding_common: String = "androidx.databinding:databinding-common:" +
      Versions.androidx_databinding

  /**
   * https://developer.android.com/studio
   */
  const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
      Versions.androidx_databinding

  const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
      Versions.androidx_databinding

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
      Versions.legacy_support_v4

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:" +
      Versions.androidx_lifecycle

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_testing: String = "androidx.room:room-testing:" + Versions.androidx_room

  /**
   * https://developer.android.com/testing
   */
  const val idling_concurrent: String = "androidx.test.espresso.idling:idling-concurrent:" +
      Versions.idling_concurrent

  /**
   * https://developer.android.com/testing
   */
  const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val espresso_idling_resource: String = "androidx.test.espresso:espresso-idling-resource:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val junit: String = "androidx.test.ext:junit:" + Versions.junit

  /**
   * https://developer.android.com/testing
   */
  const val uiautomator: String = "androidx.test.uiautomator:uiautomator:" + Versions.uiautomator

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:" + Versions.work_runtime_ktx

  const val multidex: String = "com.android.support:multidex:" + Versions.multidex

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" + Versions.crashlytics

  /**
   * https://github.com/bumptech/glide
   */
  const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
      Versions.com_github_bumptech_glide

  /**
   * https://github.com/bumptech/glide
   */
  const val glide: String = "com.github.bumptech.glide:glide:" + Versions.com_github_bumptech_glide

  const val rulseset: String = "com.github.username:rulseset:" + Versions.rulseset

  const val play_services_auth: String = "com.google.android.gms:play-services-auth:" +
      Versions.play_services_auth

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android: String = "com.google.dagger:dagger-android:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
      Versions.com_google_dagger

  const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

  const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
      Versions.firebase_messaging

  const val firebase_perf: String = "com.google.firebase:firebase-perf:" + Versions.firebase_perf

  const val perf_plugin: String = "com.google.firebase:perf-plugin:" + Versions.perf_plugin

  const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

  /**
   * https://github.com/square/okhttp
   */
  const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
      Versions.logging_interceptor

  /**
   * https://github.com/square/retrofit/
   */
  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
      Versions.io_fabric_tools_gradle

  /**
   * https://github.com/ReactiveX/RxAndroid
   */
  const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

  /**
   * https://github.com/hamcrest/JavaHamcrest
   */
  const val hamcrest_integration: String = "org.hamcrest:hamcrest-integration:" +
      Versions.hamcrest_integration

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
      Versions.org_jetbrains_kotlin

  const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:" + Versions.ktlint_gradle
}
