import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val android_arch_navigation: String = "1.0.0"

  const val appcompat: String = "1.1.0"

  const val constraintlayout: String = "2.0.0-beta1"

  const val androidx_databinding: String = "3.5.0"

  const val legacy_support_v4: String = "1.0.0"

  const val androidx_lifecycle: String = "2.2.0-alpha01"

  const val recyclerview: String = "1.1.0-alpha05"

  const val androidx_room: String = "2.1.0"

  const val idling_concurrent: String = "3.2.0"

  const val androidx_test_espresso: String = "3.2.0"

  const val junit: String = "1.1.1"

  const val uiautomator: String = "2.2.0"

  const val androidx_test: String = "1.2.0"

  const val work_runtime_ktx: String = "2.2.0"

  const val multidex: String = "1.0.3"

  const val aapt2: String = "3.5.0-5435860"

  const val com_android_tools_build_gradle: String = "3.5.0"

  const val lint_gradle: String = "26.5.0"

  const val crashlytics: String = "2.10.1"

  const val com_github_bumptech_glide: String = "4.9.0"

  const val rulseset: String = "master-SNAPSHOT"

  const val play_services_auth: String = "17.0.0"

  const val material: String = "1.1.0-alpha06"

  const val com_google_dagger: String = "2.24"

  const val firebase_auth: String = "19.0.0"

  const val firebase_core: String = "17.2.0"

  const val firebase_messaging: String = "20.0.0"

  const val firebase_perf: String = "19.0.0"

  const val perf_plugin: String = "1.3.1"

  const val google_services: String = "4.3.2"

  const val logging_interceptor: String = "4.2.0"

  const val com_squareup_retrofit2: String = "2.6.1"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2" // available: "0.5.0"

  const val io_fabric_tools_gradle: String = "1.31.0"

  const val rxandroid: String = "2.1.1"

  const val hamcrest_integration: String = "1.4-atlassian-1"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val ktlint_gradle: String = "8.2.0"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.2"

  const val gradleCurrentVersion: String = "5.4.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
