object Versions {
    const val kotlin_version = "1.3.50"
    const val androidx_version = "1.0.0"
    const val retrofit_version = "2.5.0"
    const val lifecycle_version = "2.2.0-alpha01"
    const val constraint_layout_version = "2.0.0-beta1"
    const val navigation_version = "1.0.0"
    const val rxjava_version = "2.1.0"
    const val dagger_version = "2.22.1"
    const val google_play_service_version = "16.0.1"
    const val room_version = "2.1.0-beta01"
    const val glide_version = "4.9.0"
    const val firebase_version = "16.0.9"
    const val firebase_analytics_version = "17.0.0"
    const val firebase_messaging_version = "18.0.0"
    const val work_version = "2.0.1"
    const val material_version = "1.1.0-alpha06"
    const val recycler_view_version = "1.1.0-alpha05"
    const val okhttp3_version = "4.0.0-alpha01"
    const val app_compat_version = "1.1.0-alpha05"
    const val idling_resources = "3.1.1"
    const val multidex_version = "1.0.3"
    const val crashlytics_version = "2.10.1@aar"
}