package com.example.beetlestance.benji

import android.content.Context
import androidx.multidex.MultiDex
import com.crashlytics.android.Crashlytics
import com.example.beetlestance.benji.di.DaggerAppComponent
import com.example.beetlestance.benji.di.AppComponent
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication
import io.fabric.sdk.android.Fabric

/**
 * Initialization of libraries.
 */

class MainApplication : DaggerApplication() {


    override fun onCreate() {
        super.onCreate()
        // Enable Crashlytics
        Fabric.with(this,Crashlytics())
    }

    override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(base)
        // MultiDex initialised
        MultiDex.install(this)
    }

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */

    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(this)
    }

}